//In this file we are going to build the exact shape of the data that will travel across your monorepo
// 1. Task status
// 2. Task packet
// 3. Agent state
// 4. Agent domain
// 5. Agent entity

export type TaskStatus=
    | 'PENDING_CUSTOMS'  // Arrived at Border, awaiting Constitution check
    | 'QUEUED'           // Passed Customs, sitting on the Job Board (Redis)
    | 'IN_PROGRESS'      // Claimed by an Agent in the World Engine
    | 'COMPLETED'        // Successfully processed and verified
    | 'REJECTED';        // Stopped by Customs or immune system

export interface TaskPacket{
    id: string;                  // Unique UUID
    intent: string;              // The human's raw request
    context?: string;            // Optional: History injected by Jarvis
    status: TaskStatus;          // Current location in the pipeline
    result?: string;             // The final output generated by the world
    rejectionReason?: string;    // Why it was stopped (if status is REJECTED)
    createdAt: number;           // Unix timestamp
    completedAt?: number;        // Unix timestamp
}

export type AgentState=
| 'IDLE'        // Waiting for a task to claim
| 'WORKING'
| 'REPAIRING'
| 'OFFLINE'

export type AgentDomain = 
  | 'ARCHITECT'    // High-level system design
  | 'CODER'        // Direct execution and script generation
  | 'REVIEWER'     // Conflict court and code review
  | 'CUSTOMS';     // Border patrol and constitution enforcement

export interface AgentEntity {
  id: string;
  name: string;
  domain: AgentDomain;
  reputation: number;          // 0.0 to 100.0 - dictates job bidding
  systemPrompt: string;        // The core personality and instruction set
  state: AgentState;
}

